### ISSUE TITLE
Compatibility changes while testing

### ISSUE THREAD

**Issue by AJPreto** [tingxiecsu/GraphCCS#2]
Hello! I am rerunning a few of your code, just dropping a couple changes I had to make to get it to run, helpfully it will be helpful for you!

1. On your [test notebook](https://github.com/tingxiecsu/GraphCCS/blob/main/test.ipynb), the last import did not work in its original form, instead I had to change it to `from run import data_process, test_plot`. I presume the original script name might have been changed?
2. In the `model.py` script, I had to change one of the `dgllife` imports, originally it was:
`from dgllife.model.readout.weighted_sum_and_max import WeightedSumAndMax, AttentiveFPReadout`
I changed (split it) to:
```
from dgllife.model.readout.weighted_sum_and_max import WeightedSumAndMax
from dgllife.model.readout.attentivefp_readout import AttentiveFPReadout
```
Thanks for working on this!

**Comment by tingxiecsu** [comment]
Thanks for your suggestion! Regarding the import issues, it's possible that the original script has been updated or renamed, and we have made the necessary adjustments!
